# SPDX-FileCopyrightText: 2023 - 2025 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Soft Serve paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ soft_serve_uid }}"
    group: "{{ soft_serve_gid }}"
  with_items:
    - "{{ soft_serve_base_path }}"
    - "{{ soft_serve_data_path }}"

- name: Ensure Soft Serve environment variables file created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ soft_serve_base_path }}/env"
    mode: 0640
    owner: "{{ soft_serve_uid }}"
    group: "{{ soft_serve_gid }}"

- name: Ensure Soft Serve container image is pulled
  community.docker.docker_image:
    name: "{{ soft_serve_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ soft_serve_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else soft_serve_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Soft Serve container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ soft_serve_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Soft Serve systemd installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/soft-serve.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ soft_serve_identifier }}.service"
    mode: 0644
