# SPDX-FileCopyrightText: 2023 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Soft Serve installation tasks
  when: soft_serve_enabled | bool
  tags:
    - setup-all
    - setup-soft-serve
    - install-all
    - install-soft-serve
  block:
    - name: Validate Soft Serve configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Soft Serve
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Soft Serve uninstallation tasks
  when: not soft_serve_enabled | bool
  tags:
    - setup-all
    - setup-soft-serve
  block:
    - name: Uninstall Soft Serve
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
