# SPDX-FileCopyrightText: 2023 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- block:
    - when: soft_serve_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: soft_serve_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-soft-serve
    - install-all
    - install-soft-serve

- block:
    - when: not soft_serve_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-soft-serve
