# SPDX-FileCopyrightText: 2023 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Soft Serve installation tasks
  block:
    - name: Validate Soft Serve configuration
      when: soft_serve_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Soft Serve
      when: soft_serve_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-soft-serve
    - install-all
    - install-soft-serve

- name: Perform Soft Serve uninstallation tasks
  block:
    - name: Uninstall Soft Serve
      when: not soft_serve_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-soft-serve
